<?
global $rz_b2_options;
?>
<?$APPLICATION->IncludeComponent(
	"yenisite:main_spec", 
	"bitronic2", 
	array(
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "#CATALOG_IBLOCK_ID#",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"SHOW_ALL_WO_SECTION" => "Y",
		"HIDE_NOTAVAILABLE" => "Y",
		"HIDE_WITHOUTPICTURE" => "Y",
		"STICKER_NEW" => "14",
		"STICKER_HIT" => "100",
		"STICKER_BESTSELLER" => "3",
		"DEFAULT_TAB" => "SALE",
		"TABS_INDEX" => "list",
		"IMAGE_SET" => "#ELEMENT_LIST_RESIZER_SET#",
		"ELEMENT_SORT_FIELD" => "rand",
		"ELEMENT_SORT_ORDER" => "asc",
		"LIST_PRICE_SORT" => "CATALOG_PRICE_1",
		"SHOW_ELEMENT" => "N",
		"OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"PAGE_ELEMENT_COUNT" => "36",
		"LINE_ELEMENT_COUNT" => "4",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"USE_PRODUCT_QUANTITY" => "Y",
		"HIDE_BUY_IF_PROPS" => "N",
		"CONVERT_CURRENCY" => "N",
		"OFFERS_CART_PROPERTIES" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "86400",
		"CACHE_GROUPS" => "Y",
		"META_KEYWORDS" => "-",
		"META_DESCRIPTION" => "-",
		"BROWSER_TITLE" => "-",
		"ADD_SECTIONS_CHAIN" => "N",
		"COMPARE_PATH" => SITE_DIR."ajax/compare.php",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "N",
		"PAGER_TEMPLATE" => "indicators",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"IBLOCK_MAX_VOTE" => "5",
		"IBLOCK_VOTE_NAMES" => array(
			0 => "1",
			1 => "2",
			2 => "3",
			3 => "4",
			4 => "5",
			5 => "",
		),
		"DISPLAY_AS_RATING" => "rating",
		"OFFER_TREE_PROPS" => array(
		),
		"PRODUCT_PROPERTIES" => "",
		"INCLUDE_JQUERY" => "Y",
		"SHOW_AMOUNT_STORE" => "Y",
		"COMPONENT_TEMPLATE" => "bitronic2",
		"ARTICUL_PROP" => "ARTICLE",
		"PARTIAL_PRODUCT_PROPERTIES" => "Y",
		"STORE_DISPLAY_TYPE" => $rz_b2_options["store_amount_type"],
		"SB_FULL_DEFAULT" => $rz_b2_options["sb_full_default"],
	),
	false
);