<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true) die();
global $rz_b2_options;
$APPLICATION->IncludeComponent(
    "yenisite:proxy",
    "filter_tmpl_news",
    array(
        "NEWS_TEMPLATE" => "reviews",
        "COMPONENT_TEMPLATE" => "filter_tmpl_news",
        "COMPONENT_LIST" => array(
            0 => "bitrix:news.list",
            1 => "",
        ),
        "REMOVE_POSTFIX_IN_NAMES" => "N",
        "BITRIX_NEWS_LIST-IBLOCK_TYPE" => "news",
        "BITRIX_NEWS_LIST-IBLOCK_ID" => "#REVIEWS_IBLOCK_ID#",
        "BITRIX_NEWS_LIST-NEWS_COUNT" => "4",
        "RESIZER_ITEM" => "#RESIZER_REVIEW_IMG_RESIZER_SET#",
        "BITRIX_NEWS_LIST-SORT_BY1" => "ACTIVE_FROM",
        "BITRIX_NEWS_LIST-SORT_ORDER1" => "DESC",
        "BITRIX_NEWS_LIST-SORT_BY2" => "SORT",
        "BITRIX_NEWS_LIST-SORT_ORDER2" => "ASC",
        "BITRIX_NEWS_LIST-FILTER_NAME" => "",
        "BITRIX_NEWS_LIST-FIELD_CODE" => array(
            0 => "DETAIL_PICTURE",
            1 => "ACTIVE_FROM",
            2 => "SHOW_COUNTER",
            3 => "",
        ),
        "BITRIX_NEWS_LIST-PROPERTY_CODE" => array(
            0 => "",
            1 => "MORE_PHOTO",
            2 => "",
        ),
        "BITRIX_NEWS_LIST-CHECK_DATES" => "Y",
        "BITRIX_NEWS_LIST-DETAIL_URL" => "",
        "BITRIX_NEWS_LIST-AJAX_MODE" => "N",
        "BITRIX_NEWS_LIST-PREVIEW_TRUNCATE_LEN" => "",
        "BITRIX_NEWS_LIST-ACTIVE_DATE_FORMAT" => "m.d.Y",
        "BITRIX_NEWS_LIST-SET_TITLE" => "N",
        "BITRIX_NEWS_LIST-SET_BROWSER_TITLE" => "N",
        "BITRIX_NEWS_LIST-SET_META_KEYWORDS" => "N",
        "BITRIX_NEWS_LIST-SET_META_DESCRIPTION" => "N",
        "BITRIX_NEWS_LIST-SET_LAST_MODIFIED" => "N",
        "BITRIX_NEWS_LIST-INCLUDE_IBLOCK_INTO_CHAIN" => "N",
        "BITRIX_NEWS_LIST-ADD_SECTIONS_CHAIN" => "N",
        "BITRIX_NEWS_LIST-HIDE_LINK_WHEN_NO_DETAIL" => "N",
        "BITRIX_NEWS_LIST-PARENT_SECTION" => "",
        "BITRIX_NEWS_LIST-PARENT_SECTION_CODE" => "",
        "BITRIX_NEWS_LIST-INCLUDE_SUBSECTIONS" => "N",
        "BITRIX_NEWS_LIST-STRICT_SECTION_CHECK" => "N",
        "BITRIX_NEWS_LIST-CACHE_TIME" => "36000000",
        "BITRIX_NEWS_LIST-CACHE_FILTER" => "N",
        "BITRIX_NEWS_LIST-CACHE_GROUPS" => "Y",
        "BITRIX_NEWS_LIST-PAGER_TEMPLATE" => ".default",
        "BITRIX_NEWS_LIST-DISPLAY_TOP_PAGER" => "N",
        "BITRIX_NEWS_LIST-DISPLAY_BOTTOM_PAGER" => "N",
        "BITRIX_NEWS_LIST-PAGER_TITLE" => "Новости",
        "BITRIX_NEWS_LIST-PAGER_SHOW_ALWAYS" => "N",
        "BITRIX_NEWS_LIST-PAGER_DESC_NUMBERING" => "N",
        "BITRIX_NEWS_LIST-PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "BITRIX_NEWS_LIST-PAGER_SHOW_ALL" => "N",
        "BITRIX_NEWS_LIST-PAGER_BASE_LINK_ENABLE" => "N",
        "BITRIX_NEWS_LIST-SET_STATUS_404" => "N",
        "BITRIX_NEWS_LIST-SHOW_404" => "N",
        "BITRIX_NEWS_LIST-MESSAGE_404" => "",
        "BITRIX_NEWS_LIST-PROP_FOR_SHOW_ON_MAIN" => "RZ_SHOW_ON_MAIN",
        "COMPOSITE_FRAME_MODE" => "A",
        "COMPOSITE_FRAME_TYPE" => "AUTO",
    ),
    false
);
?>